% draw_tmoscillation.m
% illustrate the oscillation of transfer matrix result.
close all;
load('onetimeData/checkm_mod3.mat');
xs3 = xs;
ys3 = ys;
load('onetimeData/checkm_mod1.mat');
xs1 = xs;
ys1 = ys;
[r1, m1, b1] = regression(1./xs1, ys1);
[r3, m3, b3] = regression(1./xs3, ys3);
load('onetimeData/checkm.mat');
[r2, m2, b2] = regression(1./xs, ys);
sall = sortrows([xs(:), ys(:); xs1(:), ys1(:); xs3(:), ys3(:)]);
psize=12;unifyfigure; hold on;
plot(1./sall(:,1), sall(:,2), '-b','LineWidth', 0.5);
xlim([0, 1e-2]);
ylim([0.55 0.65]);
xv = linspace(0, 1e-2);
yv1 = m1*xv + b1;
yv2 = m2*xv + b2;
yv3 = m3*xv + b3;
plot(xv, yv1,'--k', xv, yv2, '--k', xv, yv3, '--r');
xuse = 1/303;
yupper = xuse*m1+b1;
ylower = xuse*m2+b2;
ylimit = ys3(xs3==303);
errorbar(xuse,ylimit,ylimit-ylower,yupper-ylimit, 'xr', 'LineWidth', 2, 'MarkerSize', 12);
set(gca, 'XTick', [0, xuse, 2*xuse, 10e-3]);
set(gca, 'YTick', [0.56, 0.58, 0.6, 0.62, 0.64]);
xlabel('$1/m$', 'Interpreter', 'Latex');
ylabel('\rho');
unifyfigureend;
 print(fig,'render/tmoscillation.eps','-depsc');